---
- hosts: irp2
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install packages
      apt: pkg={{ item }} state=latest
      with_items:
        - python3
        - python3-dev
        - python-dev
        - python-virtualenv
        - python-pip
        - libxml2-dev
        - libxslt-dev
        - python3-lxml
        - libz-dev
        - git
        - nginx

    - name: Configure Nginx Proxy
      template: src=nginx-irp2.conf.j2 dest=/etc/nginx/conf.d/irp2.conf
    - service: name=nginx state=restarted enabled=yes

    - file: path=~/IRP2 state=directory mode=0755
      become: no
      tags: code

    - name: Deploy application code
      copy: src=../../{{ item }} dest=~/IRP2/ mode=0755
      with_items:
        - archives
        - static
        - templates
        - dashboard.py
        - flask_extended.py
        - irp2_schema.sql
        - requirements.txt
      become: no
      tags: code

    - name: Deploy instance (no overwrite)
      copy: src=../../{{ item }} dest=~/IRP2/ mode=0755 force=no
      with_items:
        - instance
      become: no
      tags: code

    - name: Install Python packages
      pip: requirements=~/IRP2/requirements.txt virtualenv=~/irp2venv virtualenv_python=python3.4
      become: no

    - name: Stop existing application
      command: killall python
      become: no
      ignore_errors: yes

  handlers:
    - name: restart Nginx
      service: name=ntpd state=restarted
